export interface Project {
  id: string;
  title: string;
  category: string;
  description: string;
  clientType: string;
  technologies: string[];
  imageUrl: string;
  year: string;
  link?: string;
  linkType?: 'project' | 'technology' | 'client';
  detailPageUrl?: string;
}

export const categories = [
  'All',
  'Architecture',
  'Full-Stack',
  'Open Source',
  'Cloud',
  'DevOps',
  'Data Integration',
  'Automation',
];

export const projects: Project[] = [
  {
    id: 'ha-whisker',
    title: 'Whisker (Litter-Robot cards)',
    category: 'Open Source',
    description:
      'Open-source Lovelace dashboard cards for the Whisker and Litter-Robot integration in Home Assistant, giving pet owners clear visibility into litter status, cycles, and device health without leaving their smart-home UI. Built with TypeScript for the frontend stack, distributed via HACS, and maintained under the homeassistant-extras GitHub organization for easy install and updates.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/whisker/raw/main/assets/robots.png',
    year: '2026',
    link: 'https://github.com/homeassistant-extras/whisker',
    linkType: 'project',
    detailPageUrl: '/projects/ha-whisker',
  },
  {
    id: 'pawsport',
    title: 'Pawsport: Cat Travel Passport',
    category: 'Full-Stack',
    description:
      'Developed a gamified mobile app that transforms cat photography during travel into an engaging collection experience. Pawsport allows users to capture geotagged photos of cats they encounter while traveling, build a visual passport collection, track achievements, and view their stamps on an interactive map. Features include camera capture with automatic geotagging, achievement-based gamification system, interactive Mapbox map with heat visualization, streak tracking, emoji reactions, and premium subscription tier (Purrfect Pro) with RevenueCat integration. Built with React Native, Expo, Supabase backend, and Mapbox for location services.',
    clientType: 'Personal / Business',
    technologies: [
      'React Native',
      'Expo',
      'TypeScript',
      'Supabase',
      'Mapbox',
      'RevenueCat',
      'NativeWind',
      'Expo Router',
      'React Context API',
      'Expo Camera',
      'PostHog',
      'Crisp Chat',
      'iOS',
      'Android',
    ],
    imageUrl: '/assets/projects/apps/pawsport/04.png',
    year: '2025',
    link: 'https://apps.apple.com/us/app/travel-pawsport/id6754227856',
    linkType: 'project',
    detailPageUrl: '/projects/pawsport',
  },
  {
    id: 'web-canvas',
    title: 'Web Canvas: Spatial Web Browsing',
    category: 'Full-Stack',
    description:
      'Developed a revolutionary iOS/iPadOS/macOS app that transforms web browsing into a spatial experience. Web Canvas provides an infinite canvas where users can arrange browser windows, images, and ideas visually instead of juggling traditional tabs. Features include smooth pan/zoom gestures, visual connections between related content, search history management, and full WebView browsing capabilities. Built with React Native, Expo, and Shopify React Native Skia for 60fps animations.',
    clientType: 'Personal / Business',
    technologies: [
      'React Native',
      'Expo',
      'TypeScript',
      'React Native Reanimated',
      'React Native Skia',
      'NativeWind',
      'Expo Router',
      'Zustand',
      'PostHog',
      'Crisp Chat',
      'iOS',
      'iPadOS',
      'macOS',
    ],
    imageUrl: '/assets/projects/apps/webcanvas/01.png',
    year: '2025',
    link: 'https://apps.apple.com/us/app/web-canvas/id6755220973',
    linkType: 'project',
    detailPageUrl: '/projects/web-canvas',
  },
  {
    id: 'ha-room-summary-card',
    title: 'Room summary card',
    category: 'Open Source',
    description:
      'Lightweight room-level summary card that binds a handful of entities—climate, lights, occupancy, or custom sensors—into one glanceable tile per space. Fits “area overview” dashboards and reduces scrolling through long entity lists. Open-source TypeScript card for Home Assistant, shipped via HACS with sensible defaults and flexible configuration.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/room-summary-card/raw/main/docs/assets/room-cards.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/room-summary-card',
    linkType: 'project',
    detailPageUrl: '/projects/ha-room-summary-card',
  },
  {
    id: 'linkedin-content-automation',
    title: 'AI-Powered LinkedIn Content Automation System',
    category: 'Automation',
    description:
      'Built a comprehensive content automation pipeline that transforms blog content into engaging LinkedIn posts with minimal human intervention. The system automatically scrapes website content, generates AI-powered social media posts with accompanying images, and manages a complete approval workflow before publishing. Features include intelligent content selection, ChatGPT integration for post creation, automated image generation, and Microsoft Teams-based approval processes.',
    clientType: 'Digital Marketing Agency',
    technologies: [
      'Zapier',
      'ChatGPT API',
      'Browse.AI',
      'Zapier Tables',
      'Microsoft Teams',
      'OneDrive',
      'LinkedIn API',
      'Workflow Automation',
    ],
    imageUrl: '/assets/projects/linkedin-automation.png',
    year: '2025',
    link: 'https://zapier.com/',
    linkType: 'technology',
  },
  {
    id: 'sharepoint-permission-management',
    title: 'SharePoint Permission Management & Automated Onboarding',
    category: 'Automation',
    description:
      'Engineered an intelligent permission management solution that revolutionized client onboarding through automation and standardization. The system leverages Microsoft Forms and Power Automate to create a zero-touch provisioning workflow that automatically generates role-based security groups in both Microsoft 365 and SharePoint, provisions document libraries and folders with pre-populated templates, and configures custom SharePoint web parts. Reduced onboarding time from 2+ hours to under 10 minutes while achieving 100% consistency in permission structures and enhancing security compliance through standardized, auditable workflows.',
    clientType: 'Professional Services Firm',
    technologies: [
      'SharePoint Online',
      'Power Automate',
      'Microsoft Forms',
      'Microsoft Graph API',
      'Azure AD',
      'Security Groups',
      'Role-Based Access Control',
      'Workflow Automation',
      'Governance',
    ],
    imageUrl: '/assets/projects/sharepoint-client-onboarding.png',
    year: '2025',
    link: 'https://www.ctileadership.com/',
    linkType: 'client',
  },
  {
    id: 'employee-hub-modernization',
    title: 'Employee Hub Modernization & Vacation Management System',
    category: 'Full-Stack',
    description:
      'Spearheaded a complete redesign of a corporate Employee Hub, transforming it into a modern, intuitive intranet with an integrated vacation management system. Built a sophisticated time-off solution using Microsoft Forms for dynamic request submission, Power Automate for multi-level approval workflows with automatic manager routing based on org hierarchy, and Outlook Calendar integration for real-time availability checking and automatic time-off blocking. Features include escalation logic with SLA tracking, automated notifications, executive HR dashboard with analytics, and mobile-responsive self-service portal. Reduced HR administrative burden by 70% while providing employees instant visibility into time-off balances and approval status.',
    clientType: 'Healthcare Services Provider',
    technologies: [
      'SharePoint Online',
      'SharePoint Framework (SPFx)',
      'Power Automate',
      'Microsoft Forms',
      'Microsoft Graph API',
      'Outlook Calendar API',
      'Power Platform',
      'Azure AD',
      'React',
      'TypeScript',
    ],
    imageUrl: '/assets/projects/sharepoint-employee-hub.png',
    year: '2025',
    link: 'https://www.ctileadership.com/',
    linkType: 'client',
  },
  {
    id: 'sessions-programs-ai-agent',
    title: 'Sessions and Programs AI Agent',
    category: 'Full-Stack',
    description:
      'Developed an intelligent assistant using Microsoft Copilot Studio to help create, analyze, and improve client sessions and programs. The agent leverages historical session data, case studies, and content documents from SharePoint to provide data-driven insights and recommendations. Features include performance analysis, strategic agenda planning, and automated program suggestions based on successful patterns.',
    clientType: 'Professional Services Firm',
    technologies: [
      'Microsoft Copilot Studio',
      'SharePoint Online',
      'Microsoft Teams',
      'Power Platform',
      'Azure AI',
      'Microsoft Graph API',
      'Natural Language Processing',
    ],
    imageUrl: '/assets/projects/ai-agent.png',
    year: '2025',
    link: 'https://www.ctileadership.com/',
    linkType: 'client',
  },
  {
    id: 'synapse-expense-management',
    title: 'Synapse: AI-Powered Expense Management Platform',
    category: 'Full-Stack',
    description:
      'Built a comprehensive AI-powered expense management platform that automates receipt processing and expense tracking. Leverages OpenAI GPT-4o vision model to automatically extract data from receipt images with 99% accuracy, eliminating manual data entry. Features include advanced fraud detection algorithms, duplicate expense detection, team collaboration with approval workflows, comprehensive analytics dashboards, and Stripe subscription billing. Built as a secure multi-tenant SaaS application with PostgreSQL Row Level Security (RLS) policies and full test coverage using Playwright and pgTAP.',
    clientType: 'Personal / Business',
    technologies: [
      'Next.js 15',
      'React 19',
      'TypeScript',
      'Supabase',
      'PostgreSQL',
      'OpenAI API',
      'GPT-4o',
      'Stripe',
      'Google Maps API',
      'Tailwind CSS',
      'shadcn/ui',
      'Playwright',
      'pgTAP',
      'Row Level Security',
    ],
    imageUrl: '/assets/projects/synapse.png',
    year: '2025',
  },
  {
    id: 'ha-pi-hole-card',
    title: 'Pi-hole card',
    category: 'Open Source',
    description:
      'Dashboard card for Pi-hole v5 and v6 that surfaces query volume, blocked domains, and core controls alongside the rest of your Home Assistant setup. Pairs with the official Pi-hole integration so network-wide DNS filtering is visible where operators already monitor the home stack. Written in TypeScript, published for HACS, with automation-friendly entity usage.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Pi-hole',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/pi-hole-card/raw/main/assets/pihole-card.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/pi-hole-card',
    linkType: 'project',
    detailPageUrl: '/projects/ha-pi-hole-card',
  },
  {
    id: 'ha-ohm-assistant',
    title: 'Ohm Assistant',
    category: 'Open Source',
    description:
      'Modern energy and power-consumption views for Home Assistant, turning meter and circuit entities into readable charts and summaries for everyday use. Aims to make usage patterns and peaks obvious without exporting data to a separate tool. TypeScript Lovelace front end, HACS distribution, and design tuned for clarity on both phone and desktop dashboards.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Energy',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/ohm-assistant/raw/main/assets/stacked-line.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/ohm-assistant',
    linkType: 'project',
    detailPageUrl: '/projects/ha-ohm-assistant',
  },
  {
    id: 'ha-petkit-device-cards',
    title: 'PetKit device cards',
    category: 'Open Source',
    description:
      'Specialized Lovelace cards for PetKit feeders, fountains, and related hardware when using the PetKit Home Assistant integration, exposing food levels, schedules, and device health in layouts tuned for pet-care automations. Bridges the gap between vendor apps and a unified smart-home UI. Maintained as TypeScript front-end modules with HACS-based installation for the homeassistant-extras community.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/petkit-device-cards/raw/main/assets/cards.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/petkit-device-cards',
    linkType: 'project',
    detailPageUrl: '/projects/ha-petkit-device-cards',
  },
  {
    id: 'ha-adguard-card',
    title: 'AdGuard Home card',
    category: 'Open Source',
    description:
      'Control and monitor AdGuard Home from Home Assistant through a dedicated Lovelace card: filtering statistics, client activity, and common toggles in one place next to the rest of your network stack. Designed to complement the AdGuard integration entities with a focused operator view. TypeScript implementation, HACS-ready, suitable for homelab and privacy-conscious households.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'AdGuard',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/adguard-card/raw/main/assets/pihole-card.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/adguard-card',
    linkType: 'project',
    detailPageUrl: '/projects/ha-adguard-card',
  },
  {
    id: 'ha-device-card',
    title: 'Device card',
    category: 'Open Source',
    description:
      'Generic device summary card that rolls manufacturer, connectivity, battery, firmware, and key related entities into a single Lovelace card template. Cuts down repetitive per-device YAML and keeps device drill-downs consistent across integrations. Built with TypeScript for Home Assistant’s Lovelace stack, distributed through HACS, and actively used across the homeassistant-extras ecosystem.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/device-card/raw/main/docs/assets/cards.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/device-card',
    linkType: 'project',
    detailPageUrl: '/projects/ha-device-card',
  },
  {
    id: 'curious-cat-portfolio',
    title: 'Curious Cat Consulting Portfolio Website',
    category: 'Full-Stack',
    description:
      'Designed and developed a modern, responsive portfolio website showcasing software engineering expertise and project portfolio. Features include dark/light mode theming, animated sections, contact form integration, project filtering, and mobile-first responsive design. Built with React 18, TypeScript, and Tailwind CSS, deployed on Vercel with automated CI/CD and analytics integration.',
    clientType: 'Personal / Business',
    technologies: [
      'React 18',
      'TypeScript',
      'Tailwind CSS',
      'React Router',
      'Vercel Analytics',
      'Google Analytics',
      'Formspree',
      'Lucide React',
      'Responsive Design',
    ],
    imageUrl: '/assets/projects/portfolio.jpg',
    year: '2025',
    link: 'https://curiouscat.consulting',
    linkType: 'project',
  },
  {
    id: 'ha-zwave-card-set',
    title: 'Z-Wave card set (Zooz)',
    category: 'Open Source',
    description:
      'A coordinated set of custom Lovelace cards for Zooz and compatible Z-Wave devices so switches, sensors, and energy reporting look and behave consistently across the dashboard. Reduces one-off YAML and copy-paste card configs by packaging opinionated layouts for Z-Wave JS users. TypeScript implementation with HACS delivery and CI for reliable releases.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Z-Wave JS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/zwave-card-set/raw/main/assets/cards/node-info/card.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/zwave-card-set',
    linkType: 'project',
    detailPageUrl: '/projects/ha-zwave-card-set',
  },
  {
    id: 'ha-toolbar-status-chips',
    title: 'Toolbar status chips',
    category: 'Open Source',
    description:
      'Extends the Home Assistant UI with compact toolbar “chips” that reflect live entity state, driven by labels and the current URL path so the right context follows you between views. Helps power users keep alarms, modes, or critical sensors in sight without cluttering every dashboard. Implemented as a TypeScript Lovelace resource installable through HACS.',
    clientType: 'Open Source / Community',
    technologies: [
      'TypeScript',
      'Home Assistant',
      'HACS',
      'Lovelace',
      'GitHub Actions',
    ],
    imageUrl:
      'https://github.com/homeassistant-extras/toolbar-status-chips/raw/main/assets/status-patch-chips.png',
    year: '2025',
    link: 'https://github.com/homeassistant-extras/toolbar-status-chips',
    linkType: 'project',
    detailPageUrl: '/projects/ha-toolbar-status-chips',
  },
  {
    id: 'ci-cd-transformation',
    title: 'Enterprise CI/CD Transformation',
    category: 'DevOps',
    description:
      'Transformed a brittle, manual deployment process into a robust, automated CI/CD pipeline. Revamped Git workflows, implemented branch protection rules, and created standardized deployment templates. Reduced deployment time by 85% while eliminating deployment errors that had previously affected business operations.',
    clientType: 'Large Retail Corporation',
    technologies: [
      'Azure DevOps',
      'Bitbucket Pipelines',
      'Docker',
      'PowerShell',
      'YAML',
      '.NET Core',
      'Git Flow',
    ],
    imageUrl: '/assets/projects/devops.png',
    year: '2024',
  },
  {
    id: 'cloud-data-transformation',
    title: 'Digital Transformation - Ground to Cloud',
    category: 'Cloud',
    description:
      'Led a comprehensive migration from legacy on-premise applications to a scalable cloud architecture. Developed data pipeline integrations between on-premise SQL databases and cloud-based Delta Lake infrastructure. Enabled business self-service reporting through Power BI, replacing outdated SSRS and Cognos implementations.',
    clientType: 'National Retail Chain',
    technologies: [
      'Azure Data Factory',
      'Databricks',
      'Google Cloud Platform',
      'Power BI',
      'ASP.NET',
      'Microservices',
      'Hubspot Integration',
    ],
    imageUrl: '/assets/projects/delta.jpeg',
    year: '2023',
    link: 'https://learn.microsoft.com/en-us/azure/databricks/introduction/',
    linkType: 'technology',
  },
  {
    id: 'intranet-modernization',
    title: 'SharePoint Intranet Modernization',
    category: 'Full-Stack',
    description:
      'Revitalized an outdated corporate intranet by implementing modern workflows, approval processes, and security groups. Created custom PowerApps solutions to replace paper-based processes, and developed Power Automate flows to streamline business operations. Implemented proper governance and documentation to ensure long-term maintainability.',
    clientType: 'Healthcare Services Provider',
    technologies: [
      'SharePoint Online',
      'Power Apps',
      'Power Automate',
      'Microsoft Graph API',
      'Azure AD',
      'React',
      'SPFx',
    ],
    imageUrl: '/assets/projects/sharepoint.jpg',
    link: 'https://www.ctileadership.com/',
    linkType: 'client',
    year: '2025',
  },
  {
    id: 'legacy-app-modernization',
    title: 'Legacy Application Modernization',
    category: 'Architecture',
    description:
      'Transformed a suite of outdated Windows Forms applications into a modern web-based platform. Applied domain-driven design principles to restructure the application architecture while preserving business logic. Implemented a phased migration approach that minimized business disruption while delivering incremental improvements.',
    clientType: 'Financial Services Firm',
    technologies: [
      'React',
      'TypeScript',
      'ASP.NET Core API',
      'Entity Framework',
      'SQL Server',
      'Azure App Services',
      'CI/CD',
    ],
    imageUrl: '/assets/projects/modernize.jpg',
    year: '2020',
  },
  {
    id: 'gl-system-integration',
    title: 'General Ledger System Integration',
    category: 'Data Integration',
    description:
      'Orchestrated the integration between a legacy accounting system and a new enterprise DMS platform. Identified all affected systems, many with no prior documentation, and developed comprehensive migration strategies. Created validation frameworks to ensure data integrity during and after migration, resulting in zero financial discrepancies post-cutover.',
    clientType: 'Automotive Retail Group',
    technologies: [
      'SQL Server',
      'Azure Functions',
      'Dynamics AX',
      'Custom APIs',
      'PowerShell',
      'ETL Processes',
      'Data Validation Framework',
    ],
    imageUrl: '/assets/projects/d365.jpg',
    link: 'https://www.microsoft.com/en-us/dynamics-365',
    linkType: 'technology',
    year: '2022',
  },
  {
    id: 'multi-system-integration',
    title: 'Multi-System Integration Platform',
    category: 'Data Integration',
    description:
      'Designed and implemented an integration hub that connected disparate business systems (CRM, ERP, and custom applications) to enable unified data flow across the organization. Created a centralized logging and monitoring solution that provided real-time visibility into integration health and data movement.',
    clientType: 'Manufacturing Enterprise',
    technologies: [
      'Azure Service Bus',
      'Logic Apps',
      'API Management',
      'Event Grid',
      'Azure Functions',
      'Cosmos DB',
      'Application Insights',
    ],
    imageUrl: '/assets/projects/integration.png',
    link: 'https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/event-driven',
    linkType: 'technology',
    year: '2021',
  },
];
